//proyectos
export const MOSTRAR_FORMULARIO = "MOSTRAR_FORMULARIO";
export const MOSTRAR_PROYECTOS = "MOSTRAR_PROYECTOS";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTIVO = "PROYECTO_ACTIVO";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";
export const MOSTRAR_TERMINADOS = "MOSTRAR_TERMINADOS";
export const TERMINAR_PROYECTO = "TERMINAR_PROYECTO";
export const PROYECTO_ERROR = "PROYECTO_ERROR";
//tareas
export const TASK_PROYECTO = "TASK_PROYECTO";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const VALIDAR_TAREA = "VALIDAR_TAREA";
export const DELETE_TASK = "DELETE_TASK";
export const TASK_STATE = "TASK_STATE";
export const TASK_ACTUAL = "TASK_ACTUAL";
export const ACTUALIZAR_TASK = "ACTUALIZAR_TASK";
//alerta
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
//auth
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const CERRAR_SESION = "CERRAR_SESION";
//Animaciones
export const PANELAUTH = "PANELAUTH";
export const PANELNUEVO = "PANELNUEVO";
export const PANELPROYECTOS = "PANELPROYECTOS";
export const PANELTERMIANDOS = "PANELTERMIANDOS";
export const PANEL_DASHBOARD = "PANEL_DASHBOARD";
export const TODO_FALSE = "TODO_FALSE";
export const PROYECTO_NULL = "PROYECTO_NULL";
